Create signed bundles

diff --git a/create-reqbundle b/create-reqbundle
--- a/create-reqbundle
+++ b/create-reqbundle
@@ -1,12 +1,13 @@
 #!/bin/bash
 set -e
 
-if [[ "$#" == 0 || "$1" == "--help" ]]; then
-    echo 'Creates a request bundle file (a .zip file). If given, the files'
-    echo 'FILE1, FILE2, etc. will be added to the created bundle. Those files'
-    echo 'may contain additional information about your Swaptacular node.'
+if [[ "$#" != 1 || "$1" == "--help" ]]; then
+    echo 'Creates a request bundle file (a .zip file). All files and'
+    echo 'sub-directories that the "nodeinfo" directory contains, will be added'
+    echo 'to the created bundle. Those files may contain additional information'
+    echo 'about your Swaptacular node.'
     echo
-    echo 'Usage: create-reqbundle BUNDLE_FILENAME[.zip] [FILE1 FILE2 ...]'
+    echo 'Usage: create-reqbundle BUNDLE_FILENAME[.zip]'
     exit 2
 fi
 
@@ -20,6 +21,10 @@ function find_script_dir {
         [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
     done
     DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
+}
+
+function delete_temp_dir {
+    rm -rf "$temp_dir"
 }
 
 find_script_dir || exit 3
@@ -41,25 +46,16 @@ if [ ! -s "$DIR/root-ca.csr" ]; then
     echo
 fi
 
-servers_file="$DIR/servers.txt"
-
-if [ -s "$servers_file" ]; then
-    echo "Found servers.txt file. Reading network addresses from it:"
-    cat "$servers_file"
-else
-    echo 'You must specify the network address of your server(s). The network'
-    echo 'address consists of a domain name and a port number, separated by a colon.'
-    echo 'For example: "myserver.example.com:1234".'
+bundle_file=$(echo "$1" | sed s/\.zip$//).zip
+if [ -s "$bundle_file" ]; then
     echo
-    read -p 'Network address: ' server_address
-    echo "$server_address" > "$servers_file"
+    echo "ERROR: $bundle_file already exists."
+    echo
+    exit 1
 fi
 
-required_files=("$DIR/root-ca.crt" "$DIR/root-ca.csr" "$servers_file")
-bundle_file=$(echo "$1" | sed s/\.zip$//).zip
-shift
-
-for file in ${required_files[@]} "$@"; do
+required_files=("$DIR/root-ca.crt" "$DIR/root-ca.csr")
+for file in ${required_files[@]} "$DIR/nodeinfo/servers.txt"; do
     if [ ! -f "$file" ]; then
         echo
         echo "ERROR: $file does not exist."
@@ -68,14 +64,27 @@ for file in ${required_files[@]} "$@"; do
     fi
 done
 
-if [ -s "$bundle_file" ]; then
-    echo
-    echo "ERROR: $bundle_file already exists."
-    echo
-    exit 1
-fi
+temp_dir=$(mktemp -d)
+trap delete_temp_dir EXIT
 
-zip -Xj "$bundle_file" ${required_files[@]} "$@"
+echo 'Creating nodeinfo.zip file...'
+pushd . > /dev/null
+cd "$DIR/nodeinfo"
+date -I > date.txt
+zip -rX "$temp_dir/nodeinfo.zip" *
+popd > /dev/null
+echo
+
+echo 'Creating a digital signature...'
+openssl dgst -sha256 \
+    -sign "$DIR/private/root-ca.key" \
+    -out "$temp_dir/nodeinfo.signature" \
+    "$temp_dir/nodeinfo.zip"
+
+zip -Xj -n ".zip" "$bundle_file" \
+    ${required_files[@]} \
+    "$temp_dir/nodeinfo.zip" \
+    "$temp_dir/nodeinfo.signature"
 
 echo
 echo '***********************************************************************'
@@ -83,6 +92,6 @@ echo '* IMPORTANT: A new request bundle file has been created. If you want  *'
 echo '*            to establish a permanent authenticated connection with   *'
 echo '*            another Swaptacular node, you should send this file to   *'
 echo '*            the owners of the Swaptacular node, and wait for a       *'
-echo '*            corresponding response bundle.                           *'
+echo '*            signed peer certificate.                                 *'
 echo '***********************************************************************'
 echo "File location: $bundle_file"
diff --git a/sign-peercert b/sign-peercert
--- a/sign-peercert
+++ b/sign-peercert
@@ -73,6 +73,21 @@ function verify_root_crt_files {
     fi
 }
 
+function verify_nodeinfo {
+    echo
+    echo "Verifying nodeinfo's signature..."
+    temp_pubkey_file=$(mktemp)
+    echo "$crt_pubkey" > "$temp_pubkey_file"
+    if ! openssl dgst -sha256 -verify "$temp_pubkey_file" -signature "$2" "$1" 2> /dev/null; then
+        echo
+        echo 'ERROR: The signature is invalid.'
+        echo
+        rm "$temp_pubkey_file"
+        exit 1
+    fi
+    rm "$temp_pubkey_file"
+}
+
 function reserve_subnet {
     subnet=
     subnet_dir="$1"
@@ -170,6 +185,10 @@ trap delete_temp_dir EXIT
 unzip "$1" -d "$temp_dir"
 csr_file="$temp_dir/root-ca.csr"
 verify_root_crt_files "$temp_dir/root-ca.crt" "$csr_file"
+verify_nodeinfo "$temp_dir/nodeinfo.zip" "$temp_dir/nodeinfo.signature"
+echo
+unzip -d "$temp_dir/nodeinfo" "$temp_dir/nodeinfo.zip"
+rm "$temp_dir/nodeinfo.zip" "$temp_dir/nodeinfo.signature"
 
 export DN_O=$(echo "$DN" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+')
 export DN_OU=$(echo "$DN" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+')
