Check if all dependencies are installed

diff --git a/init-ca b/init-ca
--- a/init-ca
+++ b/init-ca
@@ -1,7 +1,14 @@
 #!/bin/bash
 
-# TODO: uuidgen is not available by default on Debian. It should be
-# installed by `sudo apt-get install uuid-runtime`.
+for dependency in openssl envsubst uuidgen cmp
+do
+    if ! which "$dependency" &> /dev/null; then
+        echo
+        echo "ERROR: $dependency is not installed on your system."
+        echo
+        exit 2
+    fi
+done
 
 if [[ "$#" != 0 ]]; then
     echo 'Initialises the root-CA database. Should be run once, in the beginning.'
