Work on register-peer

diff --git a/register-peer b/register-peer
--- a/register-peer
+++ b/register-peer
@@ -2,13 +2,10 @@
 set -e
 
 if [[ "$#" != 1 || "$1" == "--help" ]]; then
-    echo 'Reads a peer bundle file and updates the contents of the "peers"'
-    echo 'directory accordingly. Each peer bundle file contains a certificate'
-    echo 'which can be used to establish an authenticated connection with a'
-    echo 'given peer node. The peer bundle file may also contain additional'
-    echo 'information about the peer node.'
+    echo 'Reads a peer certificate file and updates the contents of the'
+    echo '"peers" directory accordingly.'
     echo
-    echo 'Usage: register-peer PEERBUNDLE_FILE'
+    echo 'Usage: register-peer PEERCERT_FILE'
     exit 2
 fi
 
@@ -22,10 +19,6 @@ function find_script_dir {
         [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
     done
     DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
-}
-
-function delete_temp_dir {
-    rm -rf "$temp_dir"
 }
 
 function invalid_node_type {
@@ -42,43 +35,43 @@ function invalid_certificate {
     exit 1
 }
 
+function verify_cert_file {
+    cert_count=0
+    while openssl x509 -noout &> /dev/null; do
+        cert_count=$((cert_count+1))
+    done < "$1"
+    if [[ "$cert_count" != 1 ]]; then
+        invalid_certificate
+    fi
+}
+
 function verify_issuer {
     DN=$(openssl x509 -noout -issuer -in "$1")
-    DN_O=$(echo "$DN" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+')
-    DN_OU=$(echo "$DN" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+')
-    DN_SERIAL_NUMBER=$(echo "$DN" | grep -Po '(?<=\bserialNumber = )[a-f0-9-]+')
+    DN_O=$(echo "$DN" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+' || true)
+    DN_OU=$(echo "$DN" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+' || true)
+    DN_SERIAL_NUMBER=$(echo "$DN" | grep -Po '(?<=\bserialNumber = )[a-f0-9-]+' || true)
 
-    if [[ "$DN_O" != "Swaptacular Nodes Registry" ]]; then
-        invalid_node_type
-    fi
+    [[ -n "$DN_SERIAL_NUMBER" ]] || invalid_certificate
+    [[ "$DN_O" == "Swaptacular Nodes Registry" ]] || invalid_certificate
 
-    case "$(cat "$DIR/db/nodetype")" in
+    case "$node_type" in
         "Creditors Agents")
-            if [[ "$DN_OU" != "Accounting Authorities" ]]; then
-                invalid_node_type
-            fi
+            [[ "$DN_OU" == "Accounting Authorities" ]] || invalid_node_type
             ;;
         "Debtors Agents")
-            if [[ "$DN_OU" != "Accounting Authorities" ]]; then
-                invalid_node_type
-            fi
+            [[ "$DN_OU" == "Accounting Authorities" ]] || invalid_node_type
             ;;
         "Accounting Authorities")
-            case "$DN_OU" in
-                "Creditors Agents" | "Debtors Agents")
-                    # valid
-                    ;;
-                *)
-                    invalid_node_type
-                    ;;
-            esac
+            [[ "$DN_OU" == "Creditors Agents" ]] || [[ "$DN_OU" == "Debtors Agents" ]] \
+                || invalid_node_type
             ;;
         *)
             invalid_node_type
             ;;
     esac
 
-    if [[ ! -d "$DIR/peers/$DN_SERIAL_NUMBER" ]]; then
+    peer_dir="$DIR/peers/$DN_SERIAL_NUMBER"
+    if [[ ! -d "$peer_dir" ]]; then
         echo
         echo "ERROR: Unknown peer node \"$DN_SERIAL_NUMBER\"".
         echo
@@ -90,28 +83,26 @@ function verify_issuer {
     fi
 }
 
+function verify_basic_constraints {
+    bconstraints="$(openssl x509 -noout -ext basicConstraints -in "$1")"
+    echo "$bconstraints" | grep -P '\bcritical\b' > /dev/null || invalid_certificate
+    echo "$bconstraints" | grep -P '\bCA: *TRUE\b' > /dev/null || invalid_certificate
+}
+
 function verify_subject {
     sbj_dn=$(openssl x509 -noout -subject -in "$1")
-    sbj_dn_o=$(echo "$sbj_dn" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+')
-    sbj_dn_ou=$(echo "$sbj_dn" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+')
-    sbj_dn_sn=$(echo "$sbj_dn" | grep -Po '(?<=\bserialNumber = )[a-f0-9-]+')
+    sbj_dn_o=$(echo "$sbj_dn" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+' || true)
+    sbj_dn_ou=$(echo "$sbj_dn" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+' || true)
+    sbj_dn_sn=$(echo "$sbj_dn" | grep -Po '(?<=\bserialNumber = )[a-f0-9-]+' || true)
 
-    if [[ "$sbj_dn_o" != "Swaptacular Nodes Registry" ]]; then
-        invalid_certificate
-    fi
-
-    if [[ "$sbj_dn_ou" != "$(cat "$DIR/db/nodetype")" ]]; then
-        invalid_certificate
-    fi
-
-    if [[ "$sbj_dn_sn" != "$(cat "$DIR/db/nodeid")" ]]; then
-        invalid_certificate
-    fi
+    [[ "$sbj_dn_o" == "Swaptacular Nodes Registry" ]] || invalid_certificate
+    [[ "$sbj_dn_ou" == "$node_type" ]] || invalid_certificate
+    [[ "$sbj_dn_sn" == "$(cat "$DIR/db/nodeid")" ]] || invalid_certificate
 }
 
 function verify_enddate {
     enddate_output=$(openssl x509 -noout -enddate -in "$1")
-    enddate=$(echo "$enddate_output" | grep -Po '(?<=notAfter=).*')
+    enddate=$(echo "$enddate_output" | grep -Po '(?<=notAfter=).*' || date)
     endyear=$(date --date="$enddate" "+%Y")
     thisyear=$(date "+%Y")
     aheadyear=$((thisyear+500))
@@ -125,63 +116,50 @@ function verify_enddate {
 
 find_script_dir || exit 3
 
-temp_dir=$(mktemp -d)
-trap delete_temp_dir EXIT
+echo 'Verifying peer certificate...'
+crt_file="$1"
+node_type="$(cat "$DIR/db/nodetype")"
 
-unzip "$1" -d "$temp_dir"
-crt_file="$temp_dir/sub-ca.crt"
-subnet_file="$temp_dir/subnet.txt"
-
+verify_cert_file "$crt_file"
+verify_basic_constraints "$crt_file"
 verify_issuer "$crt_file"
 verify_subject "$crt_file"
 verify_enddate "$crt_file"
 
-mkdir "$DIR/peers" 2> /dev/null || true
-peer_dir="$DIR/peers/$DN_SERIAL_NUMBER"
 ca_file="$peer_dir/root-ca.crt"
+openssl verify -trusted "$ca_file" "$crt_file" || invalid_certificate
 
-if ! openssl verify -trusted "$ca_file" "$crt_file"; then
-    invalid_certificate
+peer_crt_file="$peer_dir/sub-ca.crt"
+
+if [ -s "$peer_crt_file" ]; then
+    if  ! cmp "$crt_file" "$peer_crt_file"; then
+        echo
+        echo "ERROR: This peer has already been registered."
+        echo
+    fi
+else
+    ns_comment_ext="$(openssl x509 -noout -ext nsComment -in "$crt_file")"
+    subnet="$(echo "$ns_comment_ext" | grep -Po '(?<=\bSubnet: )[a-f0-9-]{8,16}$' || true)"
+    case "$node_type" in
+        "Creditors Agents")
+            [[ -n "$subnet" ]] || invalid_certificate
+            echo "$subnet" > "$peer_dir/masq-subnet.txt"
+            ;;
+        "Debtors Agents")
+            [[ -n "$subnet" ]] || invalid_certificate
+            echo "$subnet" > "$DIR/subnet.txt"
+            ;;
+    esac
+    cp "$crt_file" "$peer_crt_file"
 fi
 
-
-echo $DN_O
-echo $DN_OU
-echo $DN_SERIAL_NUMBER
-exit 0
-
-crt_filename=sub-ca.crt
-temp_crt_file="$temp_dir/$crt_filename"
-peerbundle_files=("$crt_filename" "subnet.txt")
 echo
-
-openssl ca \
-    -config "$DIR/root-ca.conf" \
-    -in "$csr_file" \
-    -out "$temp_crt_file" \
-    -extensions sub_ca_ext
-
-if [ -s "$temp_crt_file" ]; then
-    save_subnet "$temp_dir/subnet.txt"
-    echo "$DN_OU" > "$temp_dir/nodetype.txt"
-    pushd . > /dev/null
-    cd "$temp_dir"
-    zip -X peerbundle ${peerbundle_files[@]}
-    rm "$temp_crt_file" "$csr_file"
-    popd > /dev/null
-    mv "$temp_dir" "$peer_dir"
-
-    echo
-    echo '***********************************************************************'
-    echo '* IMPORTANT: A new peer bundle file has been created, containing the  *'
-    echo '*            certificate that you just signed. You should send this   *'
-    echo '*            file to the owner of the Swaptacular node that made the  *'
-    echo '*            certificate signing request.                             *'
-    echo '*                                                                     *'
-    echo '*            Also, do not forget to send your own request bundle      *'
-    echo '*            file as well (see the "create-reqbundle" command), so    *'
-    echo '*            that you too, could receive a signed certificate from    *'
-    echo '*            your peer node.                                          *'
-    echo '***********************************************************************'
-    echo "File location: $peer_dir/peerbundle.zip"
-fi
+echo '***********************************************************************'
+echo '* IMPORTANT: The peer certificate file has been verified and stored.  *'
+echo '*                                                                     *'
+echo '*            You should use this peer certificate as an intermediary  *'
+echo "*            certificate, together with your server's (leaf)          *"
+echo '*            certificate, to establish authenticated SSL connections  *'
+echo '*            with the peer node. See the "sign-servercert" command.   *'
+echo '***********************************************************************'
+echo "File location: $peer_crt_file"
