Work in progress on signing/generating bundles

diff --git a/sign-cert b/sign-cert
--- a/sign-cert
+++ b/sign-cert
@@ -1,8 +1,8 @@
 #!/bin/bash
 set -e
 
-function delete_temp_crt_file {
-  rm -f "$temp_crt_file"
+function delete_temp_dir {
+    rm -rf "$temp_dir"
 }
 
 function reserve_subnet {
@@ -62,42 +62,35 @@ if [[ "$#" != 1 || "$1" == "--help" ]]; then
     exit 2
 fi
 
-csr_file="$1"
-crt_file=$(echo "$csr_file" | sed s/\.csr$//).crt
 
-if [ -s "$crt_file" ]; then
-    echo
-    echo "ERROR: $crt_file file already exists."
-    echo
-    exit 1
-fi
+temp_dir=$(mktemp -d)
+trap delete_temp_dir EXIT
+
+unzip "$1" -d "$temp_dir"
+csr_file="$temp_dir/root-ca.csr"
 
 DN=$(openssl req -noout -subject -in "$csr_file")
 export DN_O=$(echo "$DN" | grep -Po '(?<=\bO = )[\sA-Za-z0-9-]+')
 export DN_OU=$(echo "$DN" | grep -Po '(?<=\bOU = )[\sA-Za-z0-9-]+')
 export DN_SERIAL_NUMBER=$(echo "$DN" | grep -Po '(?<=\bserialNumber = )[a-f0-9-]+')
 
-approved_csr_file="approved-requests/$DN_SERIAL_NUMBER.csr"
+peer_dir="peers/$DN_SERIAL_NUMBER"
 
-if [ -s "$approved_csr_file" ]; then
-    # TODO: Consider allowing the creation of a new certificate, in case the
-    # node's public key in the old, already approved CSR (Certificate
-    # Signing Request) is the same as the public key in the new CSR. This
-    # would allow for the easy renewal of expiring certificates. Although,
-    # this is not a problem when we use "eternal" certificates.
-    if ! cmp "$csr_file" "$approved_csr_file" &> /dev/null; then
-        echo
-        echo 'ERROR: A certificate signing request from the same Swaptacular'
-        echo '       node has been approved already. Signing another certificate'
-        echo '       for the same Swaptacular node can not be allowed, because'
-        echo '       this can result in a serious security breach.'
-        echo
-        exit 1
-    fi
+if [[ "$DN_SERIAL_NUMBER" == "$(cat db/nodeid)" || -d "$peer_dir" ]]; then
+    echo
+    echo 'ERROR: A certificate signing request from the Swaptacular node'
+    echo "       \"$DN_SERIAL_NUMBER\" has been approved already."
+    echo
+    echo '       Signing another certificate for the same Swaptacular node'
+    echo '       can not be allowed, because this can result in a serious'
+    echo '       security breach.'
+    exit 1
 fi
 
-temp_crt_file=$(mktemp)
-trap delete_temp_crt_file EXIT
+crt_filename=sub-ca.crt
+temp_crt_file="$temp_dir/$crt_filename"
+peerbundle_files=("$crt_filename")
+echo
 
 openssl ca \
     -config root-ca.conf \
@@ -106,13 +99,24 @@ openssl ca \
     -extensions sub_ca_ext
 
 if [ -s "$temp_crt_file" ]; then
-    cp "$csr_file" "$approved_csr_file"
-    mv "$temp_crt_file" "$crt_file"
+    pushd . > /dev/null
+    cd "$temp_dir"
+    zip -X peerbundle ${peerbundle_files[@]}
+    rm "$temp_crt_file"
+    popd > /dev/null
+    mv "$temp_dir" "$peer_dir"
+
     echo
     echo '***********************************************************************'
-    echo '* IMPORTANT: A new certificate file has been created. You can send    *'
-    echo '*            it to the owner of the Swaptacular node that made the    *'
+    echo '* IMPORTANT: A new peer bundle file has been created, containing the  *'
+    echo '*            certificate that you just signed. You should send this   *'
+    echo '*            file to the owner of the Swaptacular node that made the  *'
     echo '*            certificate signing request.                             *'
+    echo '*                                                                     *'
+    echo '*            Also, do not forget to send your own request bundle file *'
+    echo '*            as well (see the "create-reqbundle" command), so that    *'
+    echo '*            you could receive the matching certificate from your     *'
+    echo '*            peer.                                                    *'
     echo '***********************************************************************'
-    echo "File location: $crt_file"
+    echo "File location: $peer_dir/peerbundle.zip"
 fi
