Impleent save_subnet()

diff --git a/sign-cert b/sign-cert
--- a/sign-cert
+++ b/sign-cert
@@ -5,6 +5,20 @@ function delete_temp_dir {
     rm -rf "$temp_dir"
 }
 
+function invalid_node_type {
+    echo
+    echo "ERROR: The node type is invalid."
+    echo
+    exit 1
+}
+
+function can_not_reserve_subnet {
+    echo
+    echo "ERROR: Can not reserve a subnet."
+    echo
+    exit 1
+}
+
 function reserve_subnet {
     subnet_dir="$1"
     subnet_len="$2"
@@ -52,6 +66,53 @@ function reserve_exclusive_subnet {
     return "$error_code"
 }
 
+function save_subnet {
+    case "$(cat db/nodetype)" in
+        "Creditors Agents")
+            if [[ "$DN_OU" != "Accounting Authorities" ]]; then
+                invalid_node_type
+            fi
+            if ! reserve_creditor_subnet "$DN_SERIAL_NUMBER"; then
+                can_not_reserve_subnet
+            fi
+            break
+            ;;
+        "Debtors Agents")
+            if [[ "$DN_OU" != "Accounting Authorities" ]]; then
+                invalid_node_type
+            fi
+            if ! reserve_exclusive_subnet "$DN_SERIAL_NUMBER"; then
+                can_not_reserve_subnet
+            fi
+            break
+            ;;
+        "Accounting Authorities")
+            case "$DN_OU" in
+                "Creditors Agents")
+                    if ! reserve_creditor_subnet "$DN_SERIAL_NUMBER"; then
+                        can_not_reserve_subnet
+                    fi
+                    break
+                    ;;
+                "Debtors Agents")
+                    if ! reserve_debtor_subnet "$DN_SERIAL_NUMBER"; then
+                        can_not_reserve_subnet
+                    fi
+                    break
+                    ;;
+                *)
+                    invalid_node_type
+                    ;;
+            esac
+            break
+            ;;
+        *)
+            invalid_node_type
+            ;;
+    esac
+    echo "$subnet" > "$1"
+}
+
 if [[ "$#" != 1 || "$1" == "--help" ]]; then
     echo 'Generates a certificate file from a certificate signing request (CSR)'
     echo 'file. The CSR file should be created and sent to you by another'
@@ -89,7 +150,7 @@ fi
 
 crt_filename=sub-ca.crt
 temp_crt_file="$temp_dir/$crt_filename"
-peerbundle_files=("$crt_filename")
+peerbundle_files=("$crt_filename" "subnet.txt")
 echo
 
 openssl ca \
@@ -99,6 +160,7 @@ openssl ca \
     -extensions sub_ca_ext
 
 if [ -s "$temp_crt_file" ]; then
+    save_subnet "$temp_dir/subnet.txt"
     pushd . > /dev/null
     cd "$temp_dir"
     zip -X peerbundle ${peerbundle_files[@]}
@@ -113,10 +175,10 @@ if [ -s "$temp_crt_file" ]; then
     echo '*            file to the owner of the Swaptacular node that made the  *'
     echo '*            certificate signing request.                             *'
     echo '*                                                                     *'
-    echo '*            Also, do not forget to send your own request bundle file *'
-    echo '*            as well (see the "create-reqbundle" command), so that    *'
-    echo '*            you could receive the matching certificate from your     *'
-    echo '*            peer.                                                    *'
+    echo '*            Also, do not forget to send your own request bundle      *'
+    echo '*            file as well (see the "create-reqbundle" command), so    *'
+    echo '*            that you could receive a corresponding certificate from  *'
+    echo '*            your peer node.                                          *'
     echo '***********************************************************************'
     echo "File location: $peer_dir/peerbundle.zip"
 fi
